### ISSUE TITLE
Values are not getting replaced

### ISSUE THREAD

**Issue by sundareshwarank** [swdotcom/update-and-apply-kubernetes-configs#4]
Run swdotcom/update-and-apply-kubernetes-configs@v1
  with:
    k8-config-file-paths: Manifests/kub-manifest-notification.yml
    replacement-method: defined
  env:
    AZURE_CONTAINER_REGISTRY: csrltdnp
    CONTAINER_NAME: systemselector/dev/notification
    CONTAINER_RG: AZCSR-AE-DevOpsCommon-DevStg-RG01
    CLUSTER_NAME: dcetoolskubdev
    CLUSTER_RG: AZCSR-AE-DigitalCustomerEngagementTools-DevStg-RG01
    IMAGE_PULL_SECRET_NAME: csrssdevcr-secret
    DEPLOYMENT_MANIFEST_PATH: Manifests/kub-manifest-notification.yml
    PULSEURI: https://pulse-8.qtestnet.com/webhook/9ba6c333-13c1-4049-9734-04cd4bbccfca
    PROJECTID: 316[2](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:2)6
    QTESTTESTCYCLE: 281451
    RESULTSPATH: SystemSelector.API.UnitTest/TestResults/NotificationAPI_test-results.xml
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_1658965406954
    APP_ENV: TEST ON
    SOME_CONFIG: hello
Run envsubst_arg=''
  envsubst_arg=''
  if [ defined = "defined" ]; then
    envsubst_arg="$(perl -e 'print "\$$_" for grep /^[_a-zA-Z]\w*$/, keys %ENV')"
  elif [ defined = "list" ]; then
    list=()
    for env in "$***list[@]***"; do
      envsubst_arg+="\$***$env***"
    done
  fi
  k8_files=(Manifests/kub-manifest-notification.yml)
  for file in "$***k8_files[@]***"; do
    template=`cat $file | envsubst $envsubst_arg`
    echo "$template"
    echo "$template" | kubectl apply -f -
  done
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail ***0***
  env:
    AZURE_CONTAINER_REGISTRY: csrltdnp
    CONTAINER_NAME: systemselector/dev/notification
    CONTAINER_RG: AZCSR-AE-DevOpsCommon-DevStg-RG01
    CLUSTER_NAME: dcetoolskubdev
    CLUSTER_RG: AZCSR-AE-DigitalCustomerEngagementTools-DevStg-RG01
    IMAGE_PULL_SECRET_NAME: csrssdevcr-secret
    DEPLOYMENT_MANIFEST_PATH: Manifests/kub-manifest-notification.yml
    PULSEURI: https://pulse-8.qtestnet.com/webhook/9ba6c[3](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:3)33-13c1-[4](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:4)049-9734-04cd4bbccfca
    PROJECTID: 31626
    QTESTTESTCYCLE: 2814[5](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:5)1
    RESULTSPATH: SystemSelector.API.UnitTest/TestResults/NotificationAPI_test-results.xml
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_1[6](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:6)58965406954
    APP_ENV: TEST ON
    SOME_CONFIG: hello
# Create the document namespace
kind: Namespace
apiVersion: v1
metadata:
  name: notification-test
  labels:
    name: notification-test
---
# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: my-app
#   namespace: notification-test
# data:
#   APP_ENV: 'staging'
#   SOME_CONFIG: 'hello'
# ---
# Deployment for hello world pod group 1
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: notification-test           # Please always define a namespace for your microservice
  name: system-selector-api-notification-build
  labels:
    app: system-selector-api-notification-build # This title is the one used by the Service selector
  annotations:
    kubernetes.io/change-cause: $***CHANGE_CAUSE***
spec:
  selector:
    matchLabels:
      app: system-selector-api-notification-build
  replicas: 1                    # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: system-selector-api-notification-build    # This title is the one used by the Service selector
    spec:
      containers:
      - name: system-selector-api-notification-build
        image: csrltdnp.azurecr.io/systemselector/dev/notification:c5946959426ac6[7](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:7)1bb0cb24562af31d53e[8](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:8)[16](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:16)fa7 # Set this to whatever container image the microservice is based off
        ports:
        - containerPort: 80   
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: DEV
            value: $***env.APP_ENV***
          - name: DEV1
            value: $ APP_ENV

          - name: DEV2
            value: 'TEST ON'

          - name: DEV3
            value: TEST ON 

---
# Service for hello world pod group 1
# Services are referenced by other internal services as http://SERVICENAME.NAMESPACE
# in this case it would be http://hello-world1-service.backend-hw
apiVersion: v1
kind: Service
metadata:
  namespace: notification-test
  labels:
    app: system-selector-api-notification-build-service
  name: system-selector-api-notification-build-service      # This is how the service is referenced externally
spec:
  ports:
    - port: [80](https://github.com/CSR-Limited/system-selector-api-notification/runs/7550790727?check_suite_focus=true#step:8:82)
      protocol: TCP
      targetPort: 80
  selector:
    app: system-selector-api-notification-build             # This is what decides which pods are part of this service
---
# Ingress for hello world pod group 1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Make sure the correct namespace is chosen. This must correspond to where the service endpoints are
  namespace: notification-test
  name: system-selector-api-notification-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # These rewrite rules can be tricky, reach out if you need help
spec:
  # the following is required to use HTTPS on the ingress controller
  tls:
  - hosts:
    - systemselector-dev.api.csr.com.au
    secretName: systemselector-tls
  rules:
  - host: systemselector-dev.api.csr.com.au # Needed for HTTPS
    http:
      paths:
      - pathType: Prefix
        # Match the path
        path: /notification-test(/|$)(.*)
        backend:
          service:
            # Route to the correct backend service
            name: system-selector-api-notification-test-build-service
            port:
              number: 80
namespace/notification-test unchanged
deployment.apps/system-selector-api-notification-build configured
service/system-selector-api-notification-build-service unchanged
ingress.networking.k8s.io/system-selector-api-notification-ingress unchanged

**Comment by sundareshwarank** [comment]
Hello team... is any one is working on this issues?

**Comment by pbstriker38** [comment]
Hey @sundareshwarank,

Sorry for the late reply. We did not have notifications turned on for this repo. Are you still using and having issues with this action? It's a bit hard to read your pasted code since it is not in code blocks but it appears that you are not putting your ENV vars to be replaced in `${}`. For example `value: ${APP_ENV}`

**Comment by sundareshwarank** [comment]
Hi Team,

Thanks for your email we have implemented this with another way.

Regards,
Sundreshwaran K
